export const GET_BOOKS_BY_ID_REQUEST = 'GET_BOOKS_BY_ID_REQUEST';
export const GET_BOOKS_BY_ID_SUCCESS = 'GET_BOOKS_BY_ID_SUCCESS';
export const GET_BOOKS_BY_ID_FAIL = 'GET_BOOKS_BY_ID_FAIL';

export const GET_MOVIES_BY_ID_REQUEST = 'GET_MOVIES_BY_ID_REQUEST';
export const GET_MOVIES_BY_ID_SUCCESS = 'GET_MOVIES_BY_ID_SUCCESS';
export const GET_MOVIES_BY_ID_FAIL = 'GET_MOVIES_BY_ID_FAIL';

export const GET_CHARACTERS_BY_ID_REQUEST = 'GET_CHARACTERS_BY_ID_REQUEST';
export const GET_CHARACTERS_BY_ID_SUCCESS = 'GET_CHARACTERS_BY_ID_SUCCESS';
export const GET_CHARACTERS_BY_ID_FAIL = 'GET_CHARACTERS_BY_ID_FAIL';

export const GET_QUOTES_BY_ID_REQUEST = 'GET_QUOTES_BY_ID_REQUEST';
export const GET_QUOTES_BY_ID_SUCCESS = 'GET_QUOTES_BY_ID_SUCCESS';
export const GET_QUOTES_BY_ID_FAIL = 'GET_QUOTES_BY_ID_FAIL';

export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';

export const GET_PARTICULAR_CHARACTER_BY_ID_REQUEST = 'GET_PARTICULAR_CHARACTER_BY_ID_REQUEST';
export const GET_PARTICULAR_CHARACTER_BY_ID_SUCCESS = 'GET_PARTICULAR_CHARACTER_BY_ID_SUCCESS';
export const GET_PARTICULAR_CHARACTER_BY_ID_FAIL = 'GET_PARTICULAR_CHARACTER_BY_ID_FAIL';

export const SET_PAGINATION = 'SET_PAGINATION';
